### ISSUE TITLE
Github API has changed

### ISSUE THREAD

**Issue by myoung34** [mmueller/supybot-git#23]
The github API has shutdown API V2: https://github.com/blog/1160-github-api-v2-end-of-life

The code still references this code:

```
File "/home/marcus.young/repos/Supybot-0.83.4.1/plugins/Git/plugin.py", line 79, in commits
data = self._fetch_json('http://github.com/api/v2/json/commits/list/%s/%s?author=%s' % (repo,branch_path,author))
```

**Comment by mmueller** [comment]
I don't understand -- there is no explicit Github support in supybot-git. Is this a patch you applied yourself?

**Comment by myoung34** [comment]
Nope, it's a stacktrace from running @Git commits

**Comment by myoung34** [comment]
I may have submitted too quickly from a tl;dr'ed stacktrace, this might be from gitpython

**Comment by mmueller** [comment]
I don't see any direct uses of a hard-coded `github.com` URL in GitPython's code either (outside of one test case).

The file you quoted in the first message of this issue is my Git plugin, for sure, but that's not my code. Maybe you're running a fork of it?  This is a search for "github" in supybot-git's code: https://github.com/mmueller/supybot-git/search?q=github&ref=cmdform

Or is Python being clever in the stack trace and showing the value of the format string, even though it came from your git.ini file?
